apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "canarytokens-frontend.labels" . | nindent 4 }}
  name: frontend
spec:
  ports:
  - name: "8082"
    port: 8082
    targetPort: 8082
  selector:
    {{- include "canarytokens-frontend.selectorLabels" . | nindent 4 }}
status:
  loadBalancer: {}
