apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: switchboard
  name: switchboard
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: switchboard
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: switchboard
    spec:
      containers:
      - args:
        - bash
        - -c
        - rm switchboard.pid; twistd -noy switchboard.tac --pidfile=switchboard.pid
        env:
        - name: CANARY_ALERT_EMAIL_FROM_ADDRESS
        - name: CANARY_ALERT_EMAIL_FROM_DISPLAY
        - name: CANARY_ALERT_EMAIL_SUBJECT
        - name: CANARY_PUBLIC_IP
        - name: CANARY_TOKEN_RETURN
          value: fortune
        - name: CANARY_WEB_IMAGE_UPLOAD_PATH
          value: /uploads
        - name: ERROR_LOG_WEBHOOK
        - name: LOG_FILE
          value: switchboard.log
        - name: PROTOCOL
          value: https
        image: thinkst/canarytokens
        imagePullPolicy: ""
        name: switchboard
        ports:
        - containerPort: 53
        - containerPort: 53
          protocol: UDP
        - containerPort: 25
        - containerPort: 8083
        resources: {}
        volumeMounts:
        - mountPath: /uploads/
          name: frontend-claim0
        - mountPath: /logs
          name: log-volume
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: frontend-claim0
        persistentVolumeClaim:
          claimName: frontend-claim0
      - name: log-volume
        persistentVolumeClaim:
          claimName: log-volume
status: {}
