apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: switchboard
  name: switchboard
spec:
  ports:
  - name: "53"
    port: 53
    targetPort: 53
  - name: 53-udp
    port: 53
    protocol: UDP
    targetPort: 53
  - name: "25"
    port: 25
    targetPort: 25
  - name: "8083"
    port: 8083
    targetPort: 8083
  selector:
    io.kompose.service: switchboard
status:
  loadBalancer: {}
