apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    {{- include "canarytokens-redis.labels" . | nindent 4 }}
spec:
  ports:
  - name: "6379"
    port: 6379
    targetPort: 6379
  selector:
    {{- include "canarytokens-redis.selectorLabels" . | nindent 4 }}
status:
  loadBalancer: {}
