apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  name: redis-claim0
spec:
  storageClassName: "{{ .Values.storageClassName }}"
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
