apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: log-volume
spec:
  storageClassName: "{{ .Values.storageClassName }}"
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
